version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7700
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "7700:7700"
    env_file:
      - .env

volumes:
  static_volume:
  media_volume: